# Generated by Django 5.0.7 on 2024-07-13 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="WalletModel",
            new_name="Wallet",
        ),
    ]
