# Generated by Django 5.0.7 on 2024-07-14 09:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('wallet', '0004_alter_transaction_txid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='label',
            field=models.CharField(max_length=128),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['amount'], name='wallet_tran_amount_a87b0b_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['wallet'], name='wallet_tran_wallet__4da541_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['created_at'], name='wallet_tran_created_fb97c1_idx'),
        ),
        migrations.AddIndex(
            model_name='wallet',
            index=models.Index(fields=['balance'], name='wallet_wall_balance_1ea64d_idx'),
        ),
    ]
