# Generated by Django 5.0.7 on 2024-07-14 15:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('wallet', '0005_alter_wallet_label_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(
                decimal_places=8,
                help_text='Transaction amount, can be negative',
                max_digits=18,
            ),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='txid',
            field=models.CharField(
                help_text='Unique transaction ID (usually sha256 hash)',
                max_length=64,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.DecimalField(
                decimal_places=8,
                help_text='Wallet balance, cannot be negative. Can accommodate up to a 10^12 transactions of maximum amount',
                max_digits=30,
            ),
        ),
    ]
